// Exterior references only. Dimensions describe the approximate display models,
// not a trim-specific engineering specification or a product availability claim.
export const TESLA_PRODUCTS = [
  { id: 'tesla-model-3', name: 'Model 3', family: '汽车', description: '简洁车身，轻盈姿态。',
    detail: '以焕新版 Model 3 为参考，重建低风阻轿车轮廓、细长前灯、全景玻璃车顶与五辐轮圈。',
    features: ['电动轿车', '焕新版外观', '全景玻璃车顶'], aliases: ['毛豆3', 'Model3', 'Highland', '轿车'],
    appearance: '珍珠白 · 黑色玻璃顶', source: 'https://www.tesla.com/model3', dimensions: [1.85, 1.44, 4.72] },
  { id: 'tesla-model-y', name: 'Model Y', family: '汽车', description: '从城市街道，到更远的目的地。',
    detail: '以焕新版 Model Y 为参考，呈现更高的跨界车身、贯穿式前后灯带、黑色轮拱与玻璃车顶。',
    features: ['电动 SUV', '焕新版外观', '贯穿式灯带'], aliases: ['毛豆Y', 'ModelY', 'Juniper', 'SUV'],
    appearance: '冰川蓝 · 深色轮圈', source: 'https://www.tesla.com/modely', dimensions: [1.98, 1.62, 4.79] },
  { id: 'tesla-model-s', name: 'Model S', family: '汽车', description: '流线之下，藏着力量。',
    detail: '修长的溜背轿车外形，搭配宽车肩、细长灯组、玻璃车顶与多辐轮圈。保留 Model S 的低矮比例。',
    features: ['电动轿车', '溜背车身', '低矮姿态'], aliases: ['ModelS', 'Plaid', '轿车'],
    appearance: '深红金属漆 · 深色玻璃顶', source: 'https://www.tesla.com/models', dimensions: [1.98, 1.45, 5.02] },
  { id: 'tesla-model-x', name: 'Model X', family: '汽车', description: '把空间，留给每一次同行。',
    detail: '高车顶 SUV 轮廓、向上延伸的全景前风挡，以及鹰翼门的外部分缝。此构型呈现车门闭合状态。',
    features: ['电动 SUV', '全景前风挡', '鹰翼门分缝'], aliases: ['ModelX', '鹰翼门', 'SUV'],
    appearance: '珍珠白 · 深色窗框', source: 'https://www.tesla.com/modelx', dimensions: [2.0, 1.68, 5.06] },
  { id: 'tesla-cybertruck', name: 'Cybertruck', family: '汽车', description: '折面与钢，组成新的轮廓。',
    detail: '不锈钢折面车身、楔形风挡、贯穿灯带、越野轮胎与卷帘式货厢盖。以独立几何呈现皮卡的硬朗结构。',
    features: ['电动皮卡', '不锈钢折面', '越野轮胎'], aliases: ['赛博皮卡', '赛博越野旅行车', 'Cyberbeast', '皮卡'],
    appearance: '拉丝钢色 · 深灰轮拱', source: 'https://www.tesla.com/cybertruck', dimensions: [2.2, 1.92, 5.68] },
  { id: 'tesla-semi', name: 'Semi', family: '汽车', description: '让重载运输，拥有新的形状。',
    detail: '独立牵引车构型，包含高顶驾驶舱、环绕式风挡、三轴车轮、后部车架和挂车连接座，不含挂车。',
    features: ['电动卡车', '三轴牵引车', '环绕式风挡'], aliases: ['电动重卡', '半挂卡车', 'Tesla Semi', '卡车', 'truck'],
    appearance: '银白驾驶舱 · 黑色底盘', source: 'https://www.tesla.com/semi', dimensions: [2.55, 3.8, 7.4] },
  { id: 'tesla-roadster', name: 'Roadster', family: '汽车', description: '低伏地面，面向远方。',
    detail: '依据新一代 Roadster 公开展示外观重建：短车顶、宽后肩、低矮车头与运动轮圈。尺寸采用展示估算。',
    features: ['电动跑车', '公开展示构型', '玻璃车顶'], aliases: ['敞篷跑车', '跑车', '新一代 Roadster'],
    appearance: '亮红车身 · 深色车顶', source: 'https://www.tesla.com/roadster', dimensions: [2.0, 1.22, 4.45] },
  { id: 'tesla-cybercab', name: 'Cybercab', family: '汽车', description: '为两个人，重新思考出行。',
    detail: '依据 We, Robot 展示外观重建，保留金色双门车身、连续玻璃座舱、贯穿灯带与封闭式轮圈。车门为闭合构型。',
    features: ['双门车身', '公开展示构型', '封闭式轮圈'], aliases: ['Robotaxi', '机器人出租车', '无人出租车', '赛博出租车'],
    appearance: '香槟金 · 黑色玻璃舱', source: 'https://www.tesla.com/en_ca/we-robot', dimensions: [1.95, 1.45, 4.5] },
  { id: 'tesla-optimus', name: 'Optimus', family: '机器人', description: '让机械，也有人的尺度。',
    detail: '白色外壳、黑色面罩和外露关节组成的人形机器人。包含手掌、分节手指、膝部机构和双足，采用静态站立姿势。',
    features: ['人形机器人', '分节手指', '静态站姿'], aliases: ['Tesla Bot', '擎天柱', '人形机器人', 'humanoid'],
    appearance: '黑白外壳 · 公开展示外观', source: 'https://www.tesla.com/AI', dimensions: [.62, 1.73, .33] },
  { id: 'tesla-powerwall-3', name: 'Powerwall 3', family: '储能设备', description: '把能量，留在家中。',
    detail: '白色家用储能机身、深色上沿、散热细节与安装背板。以独立设备呈现，便于与其他设施组合。',
    features: ['家用储能', '白色面板', '安装背板'], aliases: ['Powerwall', '家用电池', '储能电池', '家庭能源'],
    appearance: '白色前壳 · 黑色上沿', source: 'https://www.tesla.com/powerwall', dimensions: [.61, 1.10, .193] },
  { id: 'tesla-megapack', name: 'Megapack', family: '储能设备', description: '把电力系统，收进一组模块。',
    detail: '依据 Megapack 2 XL 的柜体布局制作，包含模块舱门、通风百叶、后部散热单元与底座。柜体尺寸与内部布局为展示近似。',
    features: ['大型储能', '模块柜体', '散热阵列'], aliases: ['Megapack 2 XL', '大型电池', '储能柜', '电网储能'],
    appearance: '白色模块舱 · 深灰底座', source: 'https://www.tesla.com/megapack', dimensions: [8.8, 2.8, 1.65] },
  { id: 'tesla-supercharger-v4', name: 'Supercharger V4', family: '充电桩', description: '下一段旅程，从这里续航。',
    detail: 'V4 超级充电桩的高立柱外观、黑色正面、侧置充电连接器与长充电线。独立桩体适合布置在场景道路旁。',
    features: ['超级充电桩', 'V4 立柱', '充电线与连接器'], aliases: ['超级充电站', '超充', 'Supercharger', '充电器', 'charging'],
    appearance: '白色立柱 · 黑色正面', source: 'https://www.tesla.com/supercharger', dimensions: [.58, 1.95, .32] },
] as const

export type TeslaProductId = typeof TESLA_PRODUCTS[number]['id']
const products = new Map<string, typeof TESLA_PRODUCTS[number]>(TESLA_PRODUCTS.map(product => [product.id, product]))
export function isTeslaProductId(id: string): id is TeslaProductId { return products.has(id) }
export function teslaProduct(id: TeslaProductId) { return products.get(id)! }
